export const CART_ACTIONS_ADD_PRODUCT = "ADD_PRODUCT";
export const CART_ACTIONS_REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const CART_ACTIONS_ADD_TO_CART = "ADD_TO_CART";
export const CART_ACTIONS_REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CART_ACTIONS_LOAD_INITIAL_CART = "LOAD_INITIAL_CART";

export const loggedInUserConstants = {
  ADD_USER: "ADD_USER",
  CLEAR_USER: "CLEAR_USER",
};

export const searchResultConstants = {
  ADD_SERACH_KEYWORD: "ADD_SERACH_KEYWORD",
  CLEAR_SERACH: "CLEAR_SERACH",
  ADD_SEARCH_RESULT: "ADD_SEARCH_RESULT",
} as const;
